name: WebdriverIO - Webdriver - Examples - CucumberJS

on:
  push:
    # Only trigger if files in this path changed
    paths:
      - 'webdriver/examples/cucumberjs/**'
      - '.github/workflows/wdio.webdriver.examples.cucumberjs.yml'
      # Don't run on Markdown changes
      - '!**.md'
    branches: [ main ]
  pull_request:
    # Only trigger if files in this path changed
    paths:
      - 'webdriver/examples/cucumberjs/**'
      - '.github/workflows/wdio.webdriver.examples.cucumberjs.yml'
      # Don't run on Markdown changes
      - '!**.md'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webdriver/examples/cucumberjs/
    env:
      TB_KEY: ${{ secrets.TB_KEY }}
      TB_SECRET: ${{ secrets.TB_SECRET }}
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: webdriver/examples/cucumberjs/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test.testingbot -- --maxInstances=25
